components:
  schemas:
    Metadata:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the resource was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the resource was last updated
        createdBy:
          type: string
          description: Identifier of the user who created the resource
        updatedBy:
          type: string
          description: Identifier of the user who last updated the resource
        version:
          type: integer
          description: Version number of the resource
        isDeleted:
          type: boolean
          default: false
          description: Soft deletion flag for the resource
