openapi: 3.0.3
info:
  title: API Definitions
  description: API Definitions, documentation, examples and test cases
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Production Server
  - url: https://testing-api.example.com/v1
    description: Testing Server
  - url : https://localhost:5000/v1
    description: Local Development Server

# Paths are referenced from domains
paths: {}

# Components are referenced from their respective files
components:
  # Schema definitions
  schemas: {}
  
  # Response definitions
  responses: {}
  
  # Parameter definitions
  parameters: {}
  
  # Security scheme definitions
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT token authentication. The token should be included in the Authorization header.
        Example: Authorization: Bearer <token>
        
        Available scopes:
        * read - Read access to resources
        * write - Write access to resources (includes create, update, delete)
    
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
      description: |
        API key authentication. The key should be included in the X-API-Key header.
        Example: X-API-Key: <your-api-key>
        
        The API key provides full access to all endpoints based on the key's permissions.
        No additional scopes are required.

# Global security requirements
# Each endpoint must satisfy either bearerAuth or apiKey
security:
  - bearerAuth: []  # Empty array means no specific scopes required by default
    apiKey: []      # API key as an alternative authentication method
