openapi: 3.0.3
info:
  title: API Definitions
  description: API Definitions, documentation, examples and test cases
  version: 1.0.0

servers:
  - url: http://cat2020.lk
    description: Production Server
  - url: http://test.cat2020.lk
    description: Testing Server
  - url : http://localhost:5000
    description: Local Development Server

paths: 
  /auth:
    $ref: './domains/auth.yaml'

components:
  schemas: {}
  responses: {}
  parameters: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT token authentication. The token should be included in the Authorization header.
        Example: Authorization: Bearer <token>
        
        Available scopes:
        * read - Read access to resources
        * write - Write access to resources (includes create, update, delete)
security:
  - bearerAuth: [] 
