openapi: 3.0.0
info:
  title: Online Booking API
  description: API for managing online property bookings.
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server
  - url: http://localhost:5000/v1
    description: Local development server

security:
  - bearerAuth: []
  - apiKeyAuth: []

paths:
  /properties:
    $ref: "./online-booking/properties/properties.yaml#/paths/~1properties"
  /bookings:
    $ref: "./online-booking/bookings/bookings.yaml#/paths/~1bookings"

components:
  schemas:
    $ref: "./components/schemas.yaml"
  responses:
    $ref: "./components/responses.yaml"
  securitySchemes:
    $ref: "./components/security.yaml" 
    
